/*
 * Copyright 2026 Rockwell Automation Technologies, Inc., All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY THE PROTON CODE GENERATOR.
 */

#ifndef PROTON_PROTON_BENCH_MCU_CONNECTIONS_H
#define PROTON_PROTON_BENCH_MCU_CONNECTIONS_H

#include <stdint.h>
#include <stdbool.h>

#include "proton/transport.h"

#ifdef __cplusplus
extern "C" {
#endif


#define PROTON_NODE_MCU_NAME "mcu"
#define PROTON_NODE_MCU_NAME_LEN 3
#define PROTON_NODE_MCU_ID 0
#define PROTON_NODE_MCU_NUM_CONNECTIONS 0

#define PROTON_NODE_MCU_ENDPOINT_0_ID 0
#define PROTON_NODE_MCU_ENDPOINT_0_TRANSPORT TRANSPORT_TYPE_UDP4

#define PROTON_NODE_MCU_ENDPOINT_0_TRANSPORT_IP "10.10.10.101"
#define PROTON_NODE_MCU_ENDPOINT_0_TRANSPORT_IP_LEN 12
#define PROTON_NODE_MCU_ENDPOINT_0_TRANSPORT_IPHL 0xa0a0a65
#define PROTON_NODE_MCU_ENDPOINT_0_TRANSPORT_IPNL 0x650a0a0a
#define PROTON_NODE_MCU_ENDPOINT_0_TRANSPORT_PORT 11416



#define PROTON_NODE_PC_NAME "pc"
#define PROTON_NODE_PC_NAME_LEN 2
#define PROTON_NODE_PC_ID 1
#define PROTON_NODE_PC_NUM_CONNECTIONS 0

#define PROTON_NODE_PC_ENDPOINT_0_ID 0
#define PROTON_NODE_PC_ENDPOINT_0_TRANSPORT TRANSPORT_TYPE_UDP4

#define PROTON_NODE_PC_ENDPOINT_0_TRANSPORT_IP "10.10.10.100"
#define PROTON_NODE_PC_ENDPOINT_0_TRANSPORT_IP_LEN 12
#define PROTON_NODE_PC_ENDPOINT_0_TRANSPORT_IPHL 0xa0a0a64
#define PROTON_NODE_PC_ENDPOINT_0_TRANSPORT_IPNL 0x640a0a0a
#define PROTON_NODE_PC_ENDPOINT_0_TRANSPORT_PORT 11416




#ifdef __cplusplus
}
#endif

#endif  // PROTON_PROTON_BENCH_MCU_CONNECTIONS_H