/*
 * Copyright 2026 Rockwell Automation Technologies, Inc., All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY THE PROTON CODE GENERATOR.
 */

#ifndef PROTON_PROTON_BENCH_MCU_IDS_H
#define PROTON_PROTON_BENCH_MCU_IDS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif


#define PROTON_BUNDLE_IMU_ID 256



#define PROTON_SIGNAL_ANGULAR_X_ID 0

#define PROTON_SIGNAL_ANGULAR_Y_ID 1

#define PROTON_SIGNAL_ANGULAR_Z_ID 2

#define PROTON_SIGNAL_LINEAR_X_ID 3

#define PROTON_SIGNAL_LINEAR_Y_ID 4

#define PROTON_SIGNAL_LINEAR_Z_ID 5

#define PROTON_SIGNAL_TS_SEC_ID 6

#define PROTON_SIGNAL_TS_NSEC_ID 7

#define PROTON_SIGNAL_FRAME_ID_ID 8


#ifdef __cplusplus
}
#endif

#endif  // PROTON_PROTON_BENCH_MCU_IDS_H