/*
 * Copyright 2026 Rockwell Automation Technologies, Inc., All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY THE PROTON CODE GENERATOR.
 */

#ifndef PROTON_REGISTRY_SIZES_H
#define PROTON_REGISTRY_SIZES_H

#ifdef __cplusplus
extern "C" {
#endif

# define PROTON_SIGNAL_REGISTRY_SIZE 10
# define PROTON_BUNDLE_REGISTRY_SIZE 1
# define PROTON_NODE_REGISTRY_SIZE 2

// Capacities

#define PROTON_SIGNAL_ANGULAR_X_CAPACITY 0

#define PROTON_SIGNAL_ANGULAR_Y_CAPACITY 0

#define PROTON_SIGNAL_ANGULAR_Z_CAPACITY 0

#define PROTON_SIGNAL_LINEAR_X_CAPACITY 0

#define PROTON_SIGNAL_LINEAR_Y_CAPACITY 0

#define PROTON_SIGNAL_LINEAR_Z_CAPACITY 0

#define PROTON_SIGNAL_TS_SEC_CAPACITY 0

#define PROTON_SIGNAL_TS_NSEC_CAPACITY 0

#define PROTON_SIGNAL_ANG_VEL_COVAR_CAPACITY 0

#define PROTON_SIGNAL_LINEAR_ACCEL_COVAR_CAPACITY 0


#ifdef __cplusplus
}
#endif

#endif  // PROTON_REGISTRY_SIZES_H