/*
 * Copyright 2026 Rockwell Automation Technologies, Inc., All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY THE PROTON CODE GENERATOR.
 */

#include "proton/transport.h"
#include "proton/registry.h"
#include "proton/node_manager.h"
#include "target_connections.h"

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

static const proton_endpoint_t g_target_connections[] = {








{
  .node_id = PROTON_NODE_PC_ID,
  .endpoint_id = PROTON_NODE_PC_ENDPOINT_0_ID,
  .transport_type = PROTON_NODE_PC_ENDPOINT_0_TRANSPORT
},







};

proton_node_t g_target_node = {
  .id = PROTON_NODE_MCU_ID,
  .destination_peers = g_target_connections,
  .num_peers = (uint8_t)(sizeof(g_target_connections) / sizeof(g_target_connections[0])),
};