/*
 * Copyright 2026 Rockwell Automation Technologies, Inc., All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * THIS FILE WAS GENERATED BY THE PROTON CODE GENERATOR.
 */

#include "proton/registry.h"
#include "proton/proton_config.h"
#include "target_registry_sizes.h"
#include "target_registry_ids.h"

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>



// Buffers for signals that are repeated, such as strings and bytes


















// Buffers to act as a decode space for repeated-type signals


















signal_desc_t g_signal_registry[PROTON_SIGNAL_REGISTRY_SIZE] = {

  {
    .id = PROTON_SIGNAL_ANGULAR_X_ID,
    .type = PROTON_FLOAT,
    .signal.id = PROTON_SIGNAL_ANGULAR_X_ID,
    .signal.which_signal = proton_Signal_float_value_tag,
    
    .signal.signal.float_value = 0.0f,
    .value_size = sizeof(float),
    .capacity = 0,
    .signal_decode_buffer = {
      .data = NULL,
      .len = 0,
    },
    
  },

  {
    .id = PROTON_SIGNAL_ANGULAR_Y_ID,
    .type = PROTON_FLOAT,
    .signal.id = PROTON_SIGNAL_ANGULAR_Y_ID,
    .signal.which_signal = proton_Signal_float_value_tag,
    
    .signal.signal.float_value = 0.0f,
    .value_size = sizeof(float),
    .capacity = 0,
    .signal_decode_buffer = {
      .data = NULL,
      .len = 0,
    },
    
  },

  {
    .id = PROTON_SIGNAL_ANGULAR_Z_ID,
    .type = PROTON_FLOAT,
    .signal.id = PROTON_SIGNAL_ANGULAR_Z_ID,
    .signal.which_signal = proton_Signal_float_value_tag,
    
    .signal.signal.float_value = 0.0f,
    .value_size = sizeof(float),
    .capacity = 0,
    .signal_decode_buffer = {
      .data = NULL,
      .len = 0,
    },
    
  },

  {
    .id = PROTON_SIGNAL_LINEAR_X_ID,
    .type = PROTON_FLOAT,
    .signal.id = PROTON_SIGNAL_LINEAR_X_ID,
    .signal.which_signal = proton_Signal_float_value_tag,
    
    .signal.signal.float_value = 0.0f,
    .value_size = sizeof(float),
    .capacity = 0,
    .signal_decode_buffer = {
      .data = NULL,
      .len = 0,
    },
    
  },

  {
    .id = PROTON_SIGNAL_LINEAR_Y_ID,
    .type = PROTON_FLOAT,
    .signal.id = PROTON_SIGNAL_LINEAR_Y_ID,
    .signal.which_signal = proton_Signal_float_value_tag,
    
    .signal.signal.float_value = 0.0f,
    .value_size = sizeof(float),
    .capacity = 0,
    .signal_decode_buffer = {
      .data = NULL,
      .len = 0,
    },
    
  },

  {
    .id = PROTON_SIGNAL_LINEAR_Z_ID,
    .type = PROTON_FLOAT,
    .signal.id = PROTON_SIGNAL_LINEAR_Z_ID,
    .signal.which_signal = proton_Signal_float_value_tag,
    
    .signal.signal.float_value = 0.0f,
    .value_size = sizeof(float),
    .capacity = 0,
    .signal_decode_buffer = {
      .data = NULL,
      .len = 0,
    },
    
  },

  {
    .id = PROTON_SIGNAL_TS_SEC_ID,
    .type = PROTON_INT64,
    .signal.id = PROTON_SIGNAL_TS_SEC_ID,
    .signal.which_signal = proton_Signal_int64_value_tag,
    
    .signal.signal.int64_value = 0,
    .value_size = sizeof(int64_t),
    .capacity = 0,
    .signal_decode_buffer = {
      .data = NULL,
      .len = 0,
    },
    
  },

  {
    .id = PROTON_SIGNAL_TS_NSEC_ID,
    .type = PROTON_INT64,
    .signal.id = PROTON_SIGNAL_TS_NSEC_ID,
    .signal.which_signal = proton_Signal_int64_value_tag,
    
    .signal.signal.int64_value = 0,
    .value_size = sizeof(int64_t),
    .capacity = 0,
    .signal_decode_buffer = {
      .data = NULL,
      .len = 0,
    },
    
  },

};

bundle_desc_t g_bundle_table[PROTON_BUNDLE_REGISTRY_SIZE] = {


  {
    .bundle_id = 256,
    .producer_ids = {
      .ids = (const uint32_t[]){ 0 },
      .count = 1
    },
    .consumer_ids = {
      .ids = (const uint32_t[]){ 1 },
      .count = 1
    },
    .signal_ids = {
      .ids = (const uint32_t[]){ 0, 1, 2, 3, 4, 5, 6, 7 },
      .count = 8
    },
    .last_send_ms = 0,
    .period_ms = 0,
    .send_now = false,
    .callback = { NULL, NULL },
  },


};

// Calculate max signals in any bundle for shared encode/decode buffer







// Shared encode/decode buffer sized to largest bundle
static proton_Signal g_encode_decode_buffer[8] = {};

// Scratch buffer used as a temporary decode target for string/bytes signals
static uint8_t g_signal_decode_scratch[PROTON_SCRATCH_BUFFER_SIZE];

proton_registry_t g_proton_registry = {
  .bundle_table = g_bundle_table,
  .bundle_count = PROTON_BUNDLE_REGISTRY_SIZE,
  .encode_decode_buffer = g_encode_decode_buffer,
  .encode_decode_buffer_count = 8,
  .signal_registry = g_signal_registry,
  .signal_count = PROTON_SIGNAL_REGISTRY_SIZE,
  .signal_scratch_buffer = g_signal_decode_scratch,
  .signal_scratch_buffer_size = PROTON_SCRATCH_BUFFER_SIZE,
};